name: Build new container

# This workflow is triggered on pushes to the repository.
on: [push,pull_request]

jobs:
  my-job:
    name: Checkout and build.sh
    runs-on: [ self-hosted, linux ]
    steps:
    - uses: actions/checkout@v2
    - name: Runi build-script
      shell: bash
      working-directory: ./hosts
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: echo $PATH
