name: Build and print a greeting

# This workflow is triggered on pushes to the repository.
on: [push,pull_request]

jobs:
  my-job:
    name: execute
    runs-on: [ self-hosted, linux ]
    steps:
    - uses: actions/checkout@test
    - name: Run build-script
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        bash build.sh
