name: Test

on:
  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  sync-and-process:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your forked repo
      - name: Process Hosts File
        run: |
          FILE_PATH="alternates/fakenews-gambling-porn-social/hosts"
          echo "$FILE_PATH"
          echo "Hello!!!"
